# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Keyan Pishdadian
#tagline:
#description:      
baseurl:          /

author:
  name:           'Keyan Pishdadian'
  url:            https://www.keyanp.com

paginate:         5

# Custom vars
version:          2.1.0

github:           https://www.github.com/